jwt:
  secret: 'jwt secret here'

GOOGLE_API_KEY: 'google translate api key here'

server:
  port: 5050

spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false